version: '3.8'

services:
  hangman:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
      - ./app:/workspace/app
      - ./requirements.txt:/workspace/requirements.txt
      - ./scripts:/workspace/start
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://hangman_user:hangman_pass@db:5432/hangman_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hangman_user
      POSTGRES_PASSWORD: hangman_pass
      POSTGRES_DB: hangman_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin2
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
