"""create hangman tables

Revision ID: 2c6691c3b201
Revises: 
Create Date: 2025-09-18 17:15:19.047433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6691c3b201'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_text'), 'words', ['text'], unique=True)
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('letter', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('guessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guesses_id'), 'guesses', ['id'], unique=False)
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('word_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('status', sa.String(), nullable=True))
    op.add_column('games', sa.Column('attempts_left', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_foreign_key(None, 'games', 'words', ['word_id'], ['id'])
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    op.drop_column('games', 'guessed_letters')
    op.drop_column('games', 'attempts')
    op.drop_column('games', 'is_finished')
    op.drop_column('games', 'word')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('word', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('is_finished', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('guessed_letters', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_column('games', 'completed_at')
    op.drop_column('games', 'created_at')
    op.drop_column('games', 'attempts_left')
    op.drop_column('games', 'status')
    op.drop_column('games', 'word_id')
    op.drop_column('games', 'user_id')
    op.drop_index(op.f('ix_guesses_id'), table_name='guesses')
    op.drop_table('guesses')
    op.drop_index(op.f('ix_words_text'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
